#!/usr/bin/env bash
# Prove check-glibc-floor.sh actually fails red.
#
# A gate nobody has watched fail is a gate that might be a no-op. This runs the
# real script against two committed fixtures whose only difference is the GLIBC
# version node they require, and asserts BOTH directions:
#
#   over-floor-stub.so  requires GLIBC_2.99  -> must exit non-zero AND say so
#   under-floor-stub.so requires GLIBC_2.17  -> must exit zero
#
# It also asserts the failure MESSAGE names the offending version and the
# declared floor, because "exit 1" alone does not distinguish a working gate
# from a script that fell over on a typo.
#
# The fixtures are regenerated by fixtures/make-glibc-stubs.sh; see its header
# for why an over-floor ELF cannot be built inside the bookworm container.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
gate="${here}/check-glibc-floor.sh"
# shellcheck source=ci/target-suite.env
source "${here}/target-suite.env"

failures=0
pass() { printf 'ok   %s\n' "$1"; }
fail() {
  printf 'FAIL %s\n' "$1" >&2
  failures=$((failures + 1))
}

# --- 1. over-floor ELF must fail red ---------------------------------------
out=""
rc=0
out="$(bash "${gate}" "${here}/fixtures/over-floor-stub.so" 2>&1)" || rc=$?

if ((rc == 0)); then
  fail "over-floor fixture was ACCEPTED (gate is a no-op)"
  printf '%s\n' "${out}" >&2
else
  pass "over-floor fixture rejected (exit ${rc})"
fi

if grep -q 'GLIBC_2\.99' <<<"${out}"; then
  pass "failure output names the offending version GLIBC_2.99"
else
  fail "failure output does not name GLIBC_2.99"
  printf '%s\n' "${out}" >&2
fi

if grep -q "GLIBC_${GLIBC_FLOOR}" <<<"${out}"; then
  pass "failure output names the declared floor GLIBC_${GLIBC_FLOOR}"
else
  fail "failure output does not name the declared floor GLIBC_${GLIBC_FLOOR}"
  printf '%s\n' "${out}" >&2
fi

# --- 2. under-floor ELF must pass ------------------------------------------
# The negative control. Without it, a gate that rejected EVERYTHING would still
# satisfy case 1.
rc=0
out="$(bash "${gate}" "${here}/fixtures/under-floor-stub.so" 2>&1)" || rc=$?
if ((rc == 0)); then
  pass "under-floor fixture accepted"
else
  fail "under-floor fixture was rejected (exit ${rc})"
  printf '%s\n' "${out}" >&2
fi

# --- 3. a missing file is an error, not a silent pass -----------------------
rc=0
bash "${gate}" "${here}/fixtures/does-not-exist.so" >/dev/null 2>&1 || rc=$?
if ((rc != 0)); then
  pass "absent ELF rejected"
else
  fail "absent ELF was accepted"
fi

# --- 4. no arguments is a usage error --------------------------------------
rc=0
bash "${gate}" >/dev/null 2>&1 || rc=$?
if ((rc != 0)); then
  pass "no-argument invocation rejected"
else
  fail "no-argument invocation was accepted"
fi

if ((failures > 0)); then
  echo "check-glibc-floor.test.sh: ${failures} assertion(s) failed" >&2
  exit 1
fi
echo "check-glibc-floor.test.sh: all assertions passed"
